- _config.yml
- _data/sidebars/about.yml
- _data/sidebars/contribute.yml
- _data/sidebars/main.yml
- _data/tool_and_resource_list.yml
- _data/topnav.yml
- _sass/_custom_classes.scss
- pages/about/about.md
- pages/about/contact.md
This PR will introduce the new navigation structure as seen in RDMkit. 
To have a live preview please visit [ this deployment](https://bedroesb.github.io/infectious-diseases-toolkit/)
> New structure

- _data/affiliations.yaml
- pages/about/support.md
Added European Union as a funder
Added BY-COVID funding information
Added acknowledgement to RDMkit codebase and experience
> Update Funders in Support page

- pages/about/support.md
Added link of BY-COVID [project page](https://by-covid.org/) to the mention on the project in the Support page.
> Add BY-COVID link

- _data/CONTRIBUTORS.yaml
Add my information to the contributors list
> Update contributors with my information

- pages/about/support.md
Update of funding acknowledgement text for EU funding.
> update support.md to newer EU guidelines

- contribute/index.md
on the contributions page (as a test demo)
> change repo to repository

- index.html
This PR adds an under construction banner on the landingpage.
> Under construction banner

- _sass/_bootstrap_variables.scss
- _sass/_custom_classes.scss
- _sass/_custom_variables.scss
The shadow looks a bit to hard in my opinion and there is a random use of (non)border / shadow
> Add subtle borders

- _config.yml
This will close #35 and will enable the cookie banner
> Adding google analytics

- about/contributors.md
> fix join us link

- page_guide.md
How do we want to link towards this page in the contribute?
> Create a general page guide 

- _data/news.yml
@bedroesb Is this the correct way to add a link to the contribute page?
> Add User Stories spreadsheet to news

- _data/sidebars/contribute.yml
- about/events.md
- about/news.md
- contribute/editors_checklist.md
- contribute/style_guide.md
- news edit me path (closes #67 )
- events edit me path
- code of conduct in sidebar
- editorial checklist RDMkit check (closes #65 )
- Specify about which title we talk in the style sheet, aligning with RDMkit (https://github.com/elixir-europe/rdmkit/pull/983) (closes #47)
> Some fixes and editorial checklist update

- page_guide.md
group work resulting from mini hackathon
> initial page template

- contribute/editorial_board_guide.md
Added direct link to the TEMPLATE_page.md file. In the future, the TEMPLATE_showcase.md link and mention will have to be added to the list.
> update reference to TEMPLATE_page.md

- CODEOWNERS
- contribute/index.md
This file will assign reviewers automatically, and at the same time they will get an email.
> Start CODEOWNERS file

- human_clinical_and_health_data/provenance.md
> Use h2 headings

- human_clinical_and_health_data/provenance.md
started adding metadata fields to page. Not finished
> add metadata fields to provenance.md

- human_biomolecular_data/data_sources.md
- human_clinical_and_health_data/data_sources.md
- pathogen_characterisation/data_sources.md
- social_and_economic_impact/data_sources.md
Template for the data sources pages related to each of the categories.
> New template for data sources pages

- var/conversions.py
Script was not correctly parsing the page_id's
> Bugfix tools and resources conversion script

- TEMPLATE_page.md
- _config.yml
- _sass/_bootstrap_variables.scss
- _sass/_custom_classes.scss
- _sass/_custom_variables.scss
- human_biomolecular_data/data_sources.md
- human_clinical_and_health_data/data_sources.md
- index.html
- pathogen_characterisation/data_sources.md
- social_and_economic_impact/data_sources.md
- When training or more information metadata is empty, they will not be visualized
- Better looking information tiles, related pages and navigation tiles 
- Fixed template subtitle word-break problem
- No word-art gradient like headings anymore!
Preview the changes [here](https://bedroesb.github.io/infectious-diseases-toolkit/) (you might have to delete your cache)
> Visual improvements

- CODE_OF_CONDUCT.md
Rephrasing of events mention based on comment here: https://github.com/elixir-europe/infectious-diseases-toolkit/pull/50#discussion_r1001995434
Is it what was meant @ppalagi?
> rephrasing events mention

- LICENSE
- about/index.md
closes #42
Still need to add link to Support page
> Add content to About

- _data/news.yml
Adding news item on the new About page
> New About page

- _data/CONTRIBUTORS.yaml
From #100 -- sorry merged too early!
@simleo to confirm listing
> Add Simone as contributor

- _data/CONTRIBUTORS.yaml
- about/editorial_board.md
> Add Martin Cook as editor

- _data/news.yml
> News update

- CODE_OF_CONDUCT.md
A adjustment to the text of the code of conduct
> Generalize resolution text

- about/support.md
> Add clearer distinction between RDMkit and the ETT

- human-clinical-and-health-data/provenance.md
> Add RDMkit link to metadata

- .gitignore
- _config.yml
- _data/tool_and_resource_list.yml
- _sass/_custom_classes.scss
- index.html
- national-resources/index.md
- tools-and-resources-list/index.md
- training-resources-list/index.md
> Add some functions

- contribute/style-guide.md
This has more details about grammar issues than the EC web style guide.
> Adding a link to the detailed EC style guide

- TEMPLATE-page.md
- _config.yml
- national-resources/TEMPLATE_resources.md
- showcase/TEMPLATE-showcase.md
This updates all markdown templates based on the changes from the Google Doc templates: [showcase](https://docs.google.com/document/d/165-r9VzCu-ZfhJlKy-7QWabkMMp9KIEzEBRvQcmijmA/edit#), [national](https://docs.google.com/document/d/1uS5inLcy2UA0casGR1cYABq8xqAjgm6j_POI4ylOM0o/edit#) and [page guide](https://docs.google.com/document/d/1Jd71fAKdJBax0ZVg2IkQUJ8e21jRoHjl48jytOGT5_c/edit#).
> Update all markdown templates

- .github/workflows/jekyll.yml
- Gemfile
- _config.yml
> Update gemfile to improve Ruby 3.0+ compatibility

- _data/CONTRIBUTORS.yaml
@bedroesb 
The three missing contributors from the EGA
> ega_contributors - Added 3 new contributors from EGA

- README.md
This will close #12. @martin-nc or @LianeHughes as natives have a look too ? ;)
> Start writing a better README

- _config.yml
This brings new contributor placeholders and copy to clipboard features!
> Bump version theme to 1.25.0

- TEMPLATE-page.md
- contribute/page-metadata.md
- showcase/TEMPLATE-showcase.md
> Update templates to use snake-case as page_id

- national-resources/index.md
This is modified from the text originally read for Sweden, general agreement from the national resources teams that this would be a good way to introduce the national pages for now.
> Add general introduction for national pages

- _data/news.yml
- _data/sidebars/main.yml
- national-resources/switzerland.md
and also adding the same name of Patricia as seen in the contributors file. @ppalagi Do you have Github info about Aitana Neves?
> Adding Switzerland to the sidebar/news 

- _data/CONTRIBUTORS.yaml
Updating affiliation of Katharina Lauer to the new one
> Update Katharina affiliation

- _data/main_tool_and_resource_list.csv
- _data/tool_and_resource_list.yml
This PR adds the tools for the korogenoest showcase page. Please only merge after #179
> Add korogenoest tools

- showcase/covid19-galaxy.md
Changing Sponsors to Support
Adding mention to krogenoest page now that it is live
> Add support and korogenoest

- human-biomolecular-data/data-sources.md
Reverts elixir-europe/infectious-diseases-toolkit#202
> Revert "Update data-sources.md"

- tools-and-resources-list/index.md
- training-resources-list/index.md
This will allow the website user to sort and search on the table.
> Enable data table on tools and training list page

- _data/news.yml
Update news with 2 new pages:
- Socioeconomics data sources
- Human biomolecular data analysis
> Update news release with new pages

- socioeconomic-data/data-sources.md
Removing contribute button from the page
> remove contribute button from data sources page

- socioeconomic-data/data-sources.md
Add changes to the socioeconomics data sources page:
- Make it for readable adding bullet points
- Make it more general and no so BY-COVID specific
> Socioeconomics data sources changes

- _data/CONTRIBUTORS.yaml
- socioeconomic-data/data-sources.md
Add contributors to the socioeconomics data sources page
> Add contributors to the socioeconomics data sources page

- national-resources/belgium.md
I refered to the existing ENA upload tool in the main tools table + improved the description of the Galaxy BE tool
> BE resources 

- _sass/_custom_classes.scss
With the new design it might more clear to add lines in the sidebar to separate more
> Add separator lines for sidebar sections

- showcase/linked-cohort-data.md
Make showcase lowercase (order seems fine)
> Update linked-cohort-data titles 

- national-resources/switzerland.md
> Adding national resources to switzerland.md

- _data/CONTRIBUTORS.yaml
- about/editorial-board.md
> Add past editorial members section

- _data/tool_and_resource_list.yml
Just some coherency between names.
> Some small tweaks in the tools and resources file

- data-description/pathogen-characterisation.md
- national-resources/switzerland.md
- provenance/human-clinical-and-health-data.md
> Adding training to several pages

- data-description/pathogen-characterisation.md
Adding carpentries as registry for training material
> Adding carpentries to training material in Data Description - Pathogen Characterisation

- _data/tool_and_resource_list.yml
- data-sources/human-biomolecular-data.md
Following the discussions with BY-COVID WP2 Leads, related to deliverable D2.3, I have added the Beacons with COVID-19 data explained in that deliverable.
> Update human-biomolecular-data page - Beacons

- showcase/image_analysis.md
Provided first draft of the image analysis tool showcase page that was created
> filled in content for image_analysis.md

- contribute/google-doc-way.md
Currently we link towards our outdated template in google docs....
> Update Google Doc templates in contribute guides

- _config.yml
- _sass/_custom_classes.scss
- index.html
This improves the national resources behavior, the scroll to top button and multiple other improvements.
https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/compare/3.0.0...3.1.1
> Update to ELIXIR Toolkit Theme 3.1.1

- _config.yml
- attributing-credit/index.md
- data-analysis/index.md
- data-description/index.md
- data-sources/index.md
- index.html
- national-resources/index.md
- provenance/index.md
- quality-control/index.md
- showcase/index.md
- tools-and-resources-list/index.md
- training-resources-list/index.md
Which includes:
* Bugfix: do not list pages that have no `page_id` in the overview list of page IDs by @bedroesb in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/275
* Fix the TOC being loaded as last making the content jump around with big pages by @bedroesb in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/277
* Bugfix: Make sure affiliations inside section navigation tiles wrap in mobile by @bedroesb in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/279
* Updating the dependencies of ETT including: Bootstrap, JQuery, DataTables and FontAwesome by @bedroesb in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/281
* Improve anchor link behavior and TOC by @bedroesb in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/282
> Move to v3.2.0 of the ETT

- _data/tool_and_resource_list.yml
- data-sources/human-biomolecular-data.md
- Some new tool mentions
- Deleting tools that are not mentioned in the text
> Small page imrpovements

- _config.yml
- _data/CONTRIBUTORS.yaml
- about/contributors.md
> Add IDTk acronym to metadata of the website.

- _config.yml
- index.html
- showcase/index.md
This brings many improvements as listed in the release notes: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/releases/tag/4.0.0
> Move to ETT v4.0.0
